---
title: "A: predictSuiattPsyCoLaus Read me first"
author: Marcel Miché
date: 2023-06-02
output:
  html_document:
    theme: yeti
    toc: false
vignette: >
  %\VignetteIndexEntry{A: predictSuiattPsyCoLaus Read me first}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## predictSuiattPsyCoLaus - Supplementary R package

suiatt = suicide attempt.

PsyCoLaus is the name of the study whose data has been used.

This supplementary R package is part of the publication 'Evaluating the clinical utility of a newly developed and validated prediction model of suicide attempts on the basis of a general community sample of adults'

### predictSuiattPsyCoLaus vignettes - Structure

This vignette provides a short explanation of how this predictSuiattPsyCoLaus package is structured.

Our predictSuiattPsyCoLaus package is structured in alphabetical order. Each vignette's name consists of an upper case letter, following the alphabetical order.

### Detailed code inspection

Best research practice guidelines recommend *to publish all code and data*, along with the main research article. Data protection laws prohibit the publication of the original data of the PsyCoLaus study. Therefore, we use the published results (see Table 1 in the research article) as the basis to simulate data, which is superficially similar to the original data. Importantly, we provide all code, starting with the simulation code (see vignette B).

## Vignettes A-E in this predictSuiattPsyCoLaus package

1. A: predictSuiattPsyCoLaus Read me first: predictSuiattPsyCoLaus introduction and overview of the other vignettes.

2. B: Simulation code

3. C: Predict suicide attempt, using logistic regression

4. D: Predict suicide attempt, using classification and regression trees (CART)

5. E: Extract and display prediction performances from logistic regression and from CART.

**References**

Boulesteix, A. L. (2015). Ten simple rules for reducing overoptimistic reporting in methodological computational research. *PLoS Computational Biology*, *11*(4), e1004191. [https://doi.org/10.1371/journal.pcbi.1004191](https://doi.org/10.1371/journal.pcbi.1004191)



